### ISSUE TITLE
更新文档失败，返回404

### ISSUE THREAD

**Issue by liaofeng** [yanheven/ali-opensearch-sdk#2]
大致代码如下：

```
def delete_doc():
    table_name = 'table_name'
    items = [
        {
            "cmd": "delete",
            "fields": {
                "id": "1"
            }
        }
    ]
    items = json.dumps(items)
    client.data.create(table_name, items)
```

阿里云返回的信息:

```{u'status': u'FAIL', u'errors': [{u'message': u'404 Not Found', u'code': 404}], u'request_id': u'1472812308120985'}```

因为 `demo.py`里面的`list_app()`能够正常工作，所以配置应该没有问题。

看起来是 url 找不到，难道是阿里云更改了 url？

**Comment by yanheven** [comment]
其他请求正常？
确保在你的opensearch产品列表找到url 
    url = 'http://opensearch-cn-hangzhou.aliyuncs.com'
这个应该是不用区域不一样。

**Comment by yanheven** [comment]
当时参加众包，我落选的，你找找当时入选的人的python sdk看看

**Comment by liaofeng** [comment]
@yanheven url 是对的，北京的。

其他的 python sdk? 没搜索到啊。

**Comment by yanheven** [comment]
https://zb.oschina.net/home/reward/025b2e5b4e9bb021

**Comment by yanheven** [comment]
https://zb.oschina.net/project/025b2e5b4e9bb021 这个

**Comment by liaofeng** [comment]
@yanheven 我看是请求的 url 错误了，参考 [API 文档](https://help.aliyun.com/document_detail/29149.html?spm=5176.doc29140.2.5.Mo7GkM)，应该请求 `/index/doc/$app_name`， 而现在请求的是 `/index/doc`

**Comment by yanheven** [comment]
已经更新
https://github.com/yanheven/ali-opensearch-sdk/commit/aae070a262a2b3ded433ffd00004f9190e5ae612

**Comment by liaofeng** [comment]
👍
